# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py311-django{30}

[testenv]
commands = {envpython} runtests.py {posargs}
deps =
    django30: Django==5.2.10
    py311-django{30}: mock
    py311-django{30}: ipdb
    py311-django{30}: coverage
    py311-django{30}: model-bakery
    py311-django{30}: typing
    py311-django{30}: attrs
    py311-django{30}: psycopg2-binary
    py311-django{30}: python-dateutil
    py311-django30: django-discover-runner